Wip master
learn-co-curriculum/react-stores-lab pull request #2
Opened 2016-09-18 19:25 UTC by alexanderGugel

2016-09-20 09:31 UTC, thomastuts commented on README.md
> +Our `<App />` component renders tow buttons and the actual counter number. If
'tow' -> 'two'

2016-09-20 09:39 UTC, thomastuts requested changes
@alexanderGugel This looks great! 🔥 

The only thing I'm really missing here is more explicit instructions. Students should be able to complete a lab by just using the lab's instructions, even if they skipped the reading. That's currently impossible (unless they start digging into tests), because some explicit instructions are missing (e.g. what should the methods in the store be called, what key should be used to store the counter value in the state, ...).

PS: `sinon` isn't installed by default in all labs, so don't forget to add it to `package.json` in both branches, or the tests won't run properly!

2016-09-21 02:13 UTC, alexanderGugel commented
@thomastuts I added some more instructions in the `README` concerning the specific objectives of the lab, but I'm still unsure how specific those should be. There are also some hints in the source code itself (e.g. that `CounterStore` should inherit from `Store` etc).

The tests themselves will print an error that `addListener` etc. should be a function, so I'm wondering if those should still be explicitly outlined in the README... It seems to give away quite a lot...

Thoughts?

2016-09-22 12:15 UTC, thomastuts commented on README.md
> +This is how it's going to look like:
`This is how it's going to look` *or* `This is what it's going to look like`

2016-09-22 12:17 UTC, thomastuts commented on README.md
> +`increment()` and `decrement()` respectively update the `counterStore` by
I know this is unintentional, but this feels like an incomplete sentence. Maybe we can end it with '... by doing the following:', or something similar?

2016-09-22 12:18 UTC, thomastuts commented on README.md
> +how a component can directly update a store.
'....there is no way a component can...' (remove the _how_)

*or*

'...there is no way for a component to directly update the store'

2016-09-22 12:19 UTC, thomastuts requested changes
@alexanderGugel This looks great, instructions are super clear now. Some really minor nits, but after that, we'll be good to merge!

2016-09-30 01:16 UTC, alexanderGugel commented
@thomastuts Fixed in 30ff804

2016-09-30 09:25 UTC, thomastuts commented
@alexanderGugel Awesome, thanks! 🎉

2016-09-30 09:26 UTC, merged